controllers:
    resource: ../../src/Controller/
    type: annotation

testBundleController:
    resource: ../../src/Umut/TestBundle/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
